name: dispatch local build

#on:
#    workflow_dispatch:
#      inputs:
#        a: { required: true, type: string}
#        b: { required: true, type: string}
#        c: { required: true, type: string}
on:
    push:
       branches: [ "develop" ]
    pull_request:
       branches: [ "develop" ]
#   # https://gist.github.com/Daniel-ltw/552b90800b07c22e4a83dfa68ada6318 ...
#     repository_dispatch:
#       types:
#         - star
#         - push
#   workflow_dispatch: # https://docs.github.com/en/actions/using-workflows/manually-running-a-workflow
#   GitHub only exposes manual triggers for workflows that are
#   ...present in the repository's default branch.
    workflow_dispatch:
        inputs:
#          environment:
#            description: 'Environment to deploy to (e.g., feature, develop, staging, trunk etc.)'
#            required: true
#            default: 'develop'
            WFDP_BUILD:
                description: 'Build number, normally YYmDD' # LATin TimeZone with months 0..9
                required: true
                default: 'YYmDD' # where 1st Jan=001, Feb=051, Mar=101,... Nov=901, Dec=951
            WFDP_USER_UPSTREAM:
                description: 'Upstream user (source of pkg)'
                required: true
#                default: 'NevilleDNZ'
                default: 'NevilleDNZ'
                type: choice
                options:
                    - 'NevilleDNZ'
                    - 'NevilleDNZ-downstream'
                    - 'NevilleDNZ-fork'
            WFDP_PRJ_UPSTREAM:
                description: 'Upstream project repo (source of pkg)'
                required: true
                default: 'algol68g'
#                default: 'gawk-downstream'
                type: choice
                options:
                    - 'gawk'
                    - 'gawk-downstream'
                    - 'chess'
                    - 'algol68g'
                    - 'algol68g-staging'
                    - 'algol68g-preview'
                    - 'algol68g-mirror'
                    - '_algol68toc'
                    - '_algol68c'
            WFDP_INCLUDE_LIBS:
                description: 'Std libraries to link in'
                required: true
                default: 'full' # All available libraries
                type: choice
                options:
                    - '_tiny' # Minimal libraries to support standard Algol68/r1
                    - '_native' # As available on building platform
                    - 'full'
            WFDP_RELEASE_NAME:
                description: 'Release to build'
                required: true
                default: '3.5.8' # MAJOR.minor.patch
                type: choice
                options:
                    - '6.2.9'
                    - '5.3.0'
                    - '5.3.0-beta'
                    - '5.2.2'
                    - '5.2.2-beta'
                    - '5.2.1'
                    - '5.2.1-beta'
                    - '1.4.0'
                    - '1.8.0'
                    - '1.9.0'
                    - '1.9.1'
                    - '1.9.2'
                    - '1.10.0'
                    - '1.10.1'
                    - '1.10.2'
                    - '1.11.0'
                    - '1.11.1'
                    - '1.12.0'
                    - '1.14.0'
                    - '1.14.1'
                    - '1.15.0'
                    - '1.15.1'
                    - '1.16.0'
                    - '1.17.0'
                    - '1.18.0'
                    - '2.0.0'
                    - '2.0.1'
                    - '2.0.2'
                    - '2.0.3'
                    - '2.1.0'
                    - '2.1.1'
                    - '2.1.2'
                    - '2.2.0'
                    - '2.3.0'
                    - '2.3.1'
                    - '2.3.2'
                    - '2.3.3'
                    - '2.3.4'
                    - '2.3.5'
                    - '2.3.6'
                    - '2.3.8'
                    - '2.3.9'
                    - '2.4.0'
                    - '2.4.1'
                    - '2.5.0'
                    - '2.6.0'
                    - '2.7.0'
                    - '2.8.0'
                    - '2.8.1'
                    - '2.8.2'
                    - '2.8.3'
                    - '2.8.4'
                    - '3.0.0'
                    - '3.0.1'
                    - '3.0.2'
                    - '3.0.3'
                    - '3.0.4'
                    - '3.0.5'
                    - '3.0.6'
                    - '3.0.7'
                    - '3.0.8'
                    - '3.1.0'
                    - '3.1.9'
                    - '3.2.0'
                    - '3.2.1'
                    - '3.3.0'
                    - '3.3.5'
                    - '3.3.16'
                    - '3.3.24'
                    - '3.4.1'
                    - '3.4.4'
                    - '3.4.5'
                    - '3.5.0'
                    - '3.5.1'
                    - '3.5.1-beta'
                    - '3.5.2'
                    - '3.5.3'
                    - '3.5.4'
                    - '3.5.5'
                    - '3.5.6'
                    - '3.5.7'
                    - '3.5.8' # MAJOR.minor.patch
                    - '3.5.9'
                    - '3.6.0'
                    - '3.7.0'
                    - '3.8.0'
                    - '3.9.0'
                    - '4.0.0'

#          WFDP_OS_REL_MACH:
#            description: 'target OS platform'
#            required: true
#            default: rhel9.3-x86_64
#            type: choice
#            options:
#              - rhel9.3-x86_64
#              - rocky9.3-aarch64
#              - debian11-aarch64
#              - raspbian12-armv7l
#              - ubuntu-latest
#              - ubuntu-20.04
#    
#          WFDP_OS:
#            description: 'target OS platform'
#            required: true
#            default: 'ubuntu'
#            type: choice
#            options:
#              - rhel
#              - raspbian
#              - debian
#              - ubuntu
#              - windows
#              - macos
#              - rocky
#              - _aws-al2
#              - _aws-al2023
#              - _archlinux-pacman
#              - _windows-cygwin
#              - _windows-wsl
#              - _windows-exe # Executable Installers (.exe)
#              - _windows-msi # Windows Installer Packages (.msi)
#              - _windows-appxbundle # Windows Store Apps (.appx, .appxbundle)
#              - _windows-application # ClickOnce Deployment (.application)
#              - _windows-chocolatey # Software Management Platforms (e.g., Chocolatey, Winget)
#              - _windows-winget # Software Management Platforms (e.g., Chocolatey, Winget)
#              - _macos-app # Application Bundles (.app)
#              - _macos-pkg # Package Files (.pkg)
#              - _macos-dmg # Disk Images (.dmg)
#              - _macos-app-store # Mac App Store Applications
#              - _freebsd-pkg # pkgsrc - 77%
#              - _openbsd-pkg # pkgsrc - 33%
#              - _netbsd-pkgsrc # pkgsrc (The NetBSD Package Collection) 16%
#              - _solaris-pkg # SVR4 Packages (System V Release 4); depricated
#              - _solaris-ips # IPS (Image Packaging System); Package Archives (.p5p)
#              - _hpux-depot # Software Distributor (SD) Packages
#              - _aix-lpp # LPP (Licensed Program Products) - fileset
#              - _aix-rpm # AIX has adopted the RPM Package Manager format
#              - _pan-os-docker
#              - _pan-linux-flatpak
#              - _pan-linux-appimage
#              - _pan-linux-snap
#              - _pan-linux-oci
#              - _macos-linux-homebrew # Homebrew Formulae
#              - _macos-linux-appimage
#    
#    # https://github.com/actions/runner-images
#          WFDP_OS_RELEASE:
#            description: 'target OS release'
#            required: true
#            default: 'latest'
#            type: choice
#            options:
#              - -latest
#              - 7.9-x86_64 # RHEL
#              - 8.9-x86_64
#              - 9.3-x86_64
#              - 12-armv7l # raspbian
#              - 11-aarch64 # debian
#              - 12-aarch64 # debian
#              - 22-04-3-amd64-vbox
#              - -20.04
#              - -22.04
#              - -24.00
#              - -14-large
#              - -14
#              - -14-xlarge
#              - -13
#              - -13-large
#              - -latest-large
#              - -13-xlarge
#              - -latest
#              - -12
#              - -12-large
#              - -11
#              - _windows-latest
#              - _windows-2022
#              - _windows-2019
#    
#          WFDP_OS_ARCH: # as per: Runner.Listener.deps.json
#            description: 'target OS arch'
#            required: true
#            default: 'x64'
#            type: choice
#            options:
#              - arm
#              - arm64
#              - x64
#              - _i686 # ? i386?
#    
#          WFDP_OS_VM:
#            description: 'target OS VM'
#            required: true
#            default: 'baremetal'
#            type: choice
#            options:
#              - baremetal
#              - vbox
#              - vmware
#              - xen

            WFDP_AUTOTOOL_CONFIGURE:
                description: 'AutoTool "configure" file - timestamp can be mangeled by git'
                required: true
                default: 'touch-now'
                type: choice
                options:
                    - force-preserve
                    - force-remake
                    - touch-now
                    - not-mangled
                    
#      jobs:
#        call-reusable-workflow:
#          uses: ./.github/workflows/autopkg_action.yml@trunk
#          with:
#            a: ${{ github.event.inputs.a }}
#            b: ${{ github.event.inputs.b }}
#            c: ${{ github.event.inputs.c }}

jobs:
    call-reusable-workflow:
        uses: ./.github/workflows/autopkg_action.yml # @trunk
        with:
            WFDP_BUILD: ${{ github.event.inputs.WFDP_BUILD }}
            WFDP_USER_UPSTREAM: ${{ github.event.inputs.WFDP_USER_UPSTREAM }}
            WFDP_PRJ_UPSTREAM: ${{ github.event.inputs.WFDP_PRJ_UPSTREAM }}
            WFDP_INCLUDE_LIBS: ${{ github.event.inputs.WFDP_INCLUDE_LIBS }}
            WFDP_RELEASE_NAME: ${{ github.event.inputs.WFDP_RELEASE_NAME }}
            WFDP_AUTOTOOL_CONFIGURE: ${{ github.event.inputs.WFDP_AUTOTOOL_CONFIGURE }}